# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190412_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='blogger_address',
        ),
    ]
