# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190412_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogger_desc',
            field=models.TextField(),
        ),
    ]
