# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190412_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogger_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
